service: lambda-member-v5user-skill-sync
disabledDeprecations:
  - LOAD_VARIABLES_FROM_ENV_FILES
provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs12.x
  memorySize: 256
  timeout: 100
  lambdaHashingVersion: 20201221

package:
  patterns:
    - src/**
    - '!.git/**'
    - '!test/**'

plugins:
  - serverless-dotenv-plugin

functions:
  syncSkills:
    handler: index.handle
    name: member-v5user-skill-sync
    description: member-v5user-skill-sync
