service: lambda-member-v5user-skill-sync
provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  role: ${file(./config/${self:provider.stage}.json):LAMBDA_ROLE}
  runtime: nodejs12.x
  memorySize: 256
  timeout: 15
  environment:
   DB_AGGREGATED_SKILLS_STREAM: ${file(./config/${self:provider.stage}.json):DB_AGGREGATED_SKILLS_STREAM}
   DB_ENTERED_SKILLS_STREAM: ${file(./config/${self:provider.stage}.json):DB_ENTERED_SKILLS_STREAM}
   TC_API_URL: ${file(./config/${self:provider.stage}.json):TC_API_URL}

functions:
 handler:
   handler: index.syncSkills
   name: member-v5user-skill-sync # optional, Deployed Lambda name
   description: member-v5user-skill-sync # The description of your function.
   events:
    - http: ANY /
